[package]
name = 'smtp'
publish = false
version = '0.1.0'
edition = '2024'

[dependencies]
email_address = '0.2.9'
tokio.workspace = true
serde.workspace = true
chrono = '0.4.42'
tracing.workspace = true
tracing-subscriber.workspace = true
