[package]
name = 'smtp'
publish = false
version = '0.1.0'
edition = '2024'

[dependencies]
email_address = "0.2.9"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.226", features = ["derive"] }
chrono = "0.4.42"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"